# Generated by Django 2.2.5 on 2019-09-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='channel_id',
            field=models.CharField(db_index=True, default=11, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
