# Generated by Django 2.2.5 on 2019-09-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousviewer',
            name='channel_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authenticatedviewer',
            name='channel_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymousviewer',
            name='ip_address',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='authenticatedviewer',
            name='opaque_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='anonymousviewer',
            unique_together={('ip_address', 'channel_id')},
        ),
        migrations.AlterUniqueTogether(
            name='authenticatedviewer',
            unique_together={('opaque_id', 'channel_id')},
        ),
    ]
